/* Allegro datafile object indexes, produced by grabber v3.0 */
/* Datafile: d:\programm\projects\asteroid\asteroid.dat */
/* Date: Sat Dec 13 23:53:17 1997 */
/* Do not hand edit! */

#define __Ammo1                          0        /* BMP  */
#define __Ammo2                          1        /* BMP  */
#define __Bar1                           2        /* BMP  */
#define __Bar2                           3        /* BMP  */
#define __Boom                           4        /* SAMP */
#define __Engine                         5        /* SAMP */
#define __Explode                        6        /* BMP  */
#define __Game_palette                   7        /* PAL  */
#define __music                          8        /* MIDI */
#define __Rock                           9        /* BMP  */
#define __Ship1                          10       /* BMP  */
#define __Ship2                          11       /* BMP  */
#define __Shoot                          12       /* SAMP */
#define __COUNT                          13

